apiVersion: v1
kind: Service
metadata:
  name: {{ template "presto.fullname" . }}
  labels:
    {{- include "presto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.config.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "presto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
